import { StyleSheet } from 'react-native';
import { PROFILES_COLORS, PROFILES_CONFIG } from '../constants/profiles.constants';

export const profilesStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: PROFILES_COLORS.background,
  },
  root: {
    flex: 1,
    position: 'relative',
  },
  topBackground: {
    height: '52%',
    backgroundColor: PROFILES_COLORS.primary,
    position: 'relative',
    overflow: 'hidden',
  },
  headerContainer: {
    alignItems: 'center',
    paddingTop: PROFILES_CONFIG.spacing.xl + 18,
  },
  logo: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: 'rgba(255, 255, 255, 0.18)',
    borderWidth: 2,
    borderColor: PROFILES_COLORS.white,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: PROFILES_CONFIG.spacing.md,
  },
  logoIcon: {
    color: PROFILES_COLORS.white,
  },
  title: {
    color: PROFILES_COLORS.white,
    fontSize: 26,
    fontWeight: '800',
    textAlign: 'center',
    marginBottom: PROFILES_CONFIG.spacing.xs,
    letterSpacing: 0.8,
  },
  subtitle: {
    color: 'rgba(255, 255, 255, 0.85)',
    fontSize: 15,
    textAlign: 'center',
  },
  topHeader: {
    position: 'absolute',
    top: PROFILES_CONFIG.spacing.xl + 6,
    left: PROFILES_CONFIG.spacing.lg,
    right: PROFILES_CONFIG.spacing.lg,
    flexDirection: 'row',
    alignItems: 'center',
  },
  backButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  decorCircleTop: {
    position: 'absolute',
    top: -80,
    left: -70,
    width: 160,
    height: 160,
    borderRadius: 80,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
  },
  decorCircleRight: {
    position: 'absolute',
    top: -60,
    right: -70,
    width: 140,
    height: 140,
    borderRadius: 70,
    backgroundColor: 'rgba(255, 255, 255, 0.18)',
  },
  bottomBackground: {
    flex: 1,
    backgroundColor: PROFILES_COLORS.background,
  },
  formWrapper: {
    position: 'absolute',
    top: 228,
    left: PROFILES_CONFIG.spacing.md,
    right: PROFILES_CONFIG.spacing.md,
    paddingBottom: PROFILES_CONFIG.spacing.lg,
  },
  formCard: {
    width: '100%',
    marginLeft: 0,
    marginRight: 0,
    maxWidth: undefined,
    backgroundColor: PROFILES_COLORS.surface,
    borderRadius: PROFILES_CONFIG.radius,
    padding: PROFILES_CONFIG.spacing.lg,
    borderWidth: 1,
    borderColor: PROFILES_COLORS.border,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.1,
    shadowRadius: 16,
    elevation: 5,
  },
  section: {
    marginBottom: PROFILES_CONFIG.spacing.md,
  },
  label: {
    color: PROFILES_COLORS.primaryDark,
    fontSize: 13,
    fontWeight: '700',
    marginBottom: PROFILES_CONFIG.spacing.xs,
    letterSpacing: 0.2,
  },
  input: {
    height: PROFILES_CONFIG.inputHeight,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: PROFILES_COLORS.border,
    backgroundColor: '#F2FAFA',
    paddingHorizontal: PROFILES_CONFIG.spacing.md,
    color: PROFILES_COLORS.text,
    fontSize: 14,
    paddingVertical: 0,
  },
  selectInput: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  selectText: {
    color: PROFILES_COLORS.text,
    fontSize: 14,
    lineHeight: PROFILES_CONFIG.inputHeight,
  },
  selectPlaceholder: {
    color: PROFILES_COLORS.textMuted,
    lineHeight: PROFILES_CONFIG.inputHeight,
  },
  selectList: {
    marginTop: PROFILES_CONFIG.spacing.xs,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: PROFILES_COLORS.border,
    backgroundColor: PROFILES_COLORS.surface,
    overflow: 'hidden',
  },
  selectItem: {
    paddingVertical: PROFILES_CONFIG.spacing.sm,
    paddingHorizontal: PROFILES_CONFIG.spacing.md,
  },
  selectItemText: {
    color: PROFILES_COLORS.primaryDark,
    fontSize: 14,
    fontWeight: '600',
  },
  selectItemActive: {
    backgroundColor: 'rgba(14, 124, 134, 0.08)',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.35)',
    justifyContent: 'center',
    paddingHorizontal: PROFILES_CONFIG.spacing.lg,
  },
  modalCard: {
    backgroundColor: PROFILES_COLORS.surface,
    borderRadius: PROFILES_CONFIG.radius,
    paddingVertical: PROFILES_CONFIG.spacing.md,
    borderWidth: 1,
    borderColor: PROFILES_COLORS.border,
  },
  modalTitle: {
    color: PROFILES_COLORS.primaryDark,
    fontSize: 16,
    fontWeight: '700',
    paddingHorizontal: PROFILES_CONFIG.spacing.lg,
    paddingBottom: PROFILES_CONFIG.spacing.sm,
  },
  modalDivider: {
    height: 1,
    backgroundColor: PROFILES_COLORS.border,
  },
  inputMultiline: {
    height: 84,
    paddingTop: PROFILES_CONFIG.spacing.sm,
  },
  photoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: PROFILES_CONFIG.spacing.md,
  },
  photoPlaceholder: {
    width: PROFILES_CONFIG.photoSize,
    height: PROFILES_CONFIG.photoSize,
    borderRadius: PROFILES_CONFIG.photoSize / 2,
    backgroundColor: PROFILES_COLORS.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  photoText: {
    color: PROFILES_COLORS.white,
    fontSize: 12,
    fontWeight: '700',
  },
  buttons: {
    flexDirection: 'row',
    gap: PROFILES_CONFIG.spacing.md,
    marginTop: PROFILES_CONFIG.spacing.md,
  },
  buttonPrimary: {
    flex: 1,
    height: 44,
    borderRadius: 14,
    backgroundColor: PROFILES_COLORS.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  buttonSecondary: {
    flex: 1,
    height: 44,
    borderRadius: 14,
    backgroundColor: PROFILES_COLORS.surface,
    borderWidth: 1,
    borderColor: PROFILES_COLORS.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  buttonPrimaryText: {
    color: PROFILES_COLORS.white,
    fontWeight: '700',
  },
  buttonSecondaryText: {
    color: PROFILES_COLORS.primary,
    fontWeight: '700',
  },
});
