import { StyleSheet } from 'react-native';
import { MENU_COLORS, MENU_CONFIG } from '../constants/menu.constants';

export const menuStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: MENU_COLORS.background,
  },
  screenContainer: {
    flex: 1,
    backgroundColor: MENU_COLORS.background,
    paddingHorizontal: MENU_CONFIG.spacing.lg,
    paddingTop: MENU_CONFIG.spacing.lg,
    paddingBottom: 90,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    zIndex: 0,
    marginBottom: MENU_CONFIG.spacing.sm,
  },
  greeting: {
    marginTop: MENU_CONFIG.spacing.md,
  },
  greetingDivider: {
    height: 1,
    backgroundColor: MENU_COLORS.border,
    marginTop: MENU_CONFIG.spacing.md,
    marginHorizontal: -MENU_CONFIG.spacing.lg,
  },
  actionArea: {
    marginTop: MENU_CONFIG.spacing.lg,
  },
  emptyState: {
    paddingVertical: MENU_CONFIG.spacing.lg,
    paddingHorizontal: MENU_CONFIG.spacing.md,
    borderRadius: 14,
    backgroundColor: 'rgba(14, 124, 134, 0.08)',
    borderWidth: 1,
    borderColor: MENU_COLORS.border,
  },
  emptyStateText: {
    color: MENU_COLORS.primaryDark,
    fontSize: 14,
    fontWeight: '600',
    textAlign: 'center',
  },
  profileCardSpacer: {
    marginBottom: MENU_CONFIG.spacing.md,
  },
  primaryAction: {
    width: '100%',
    paddingVertical: MENU_CONFIG.spacing.md,
    paddingHorizontal: MENU_CONFIG.spacing.lg,
    borderRadius: 18,
    backgroundColor: MENU_COLORS.surface,
    borderWidth: 1,
    borderColor: MENU_COLORS.border,
    flexDirection: 'row',
    alignItems: 'center',
    gap: MENU_CONFIG.spacing.md,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 4,
  },
  primaryActionIconWrap: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: MENU_COLORS.primary,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  primaryActionIcon: {
    color: MENU_COLORS.surface,
  },
  primaryActionBadge: {
    position: 'absolute',
    top: -6,
    right: -6,
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: MENU_COLORS.surface,
    alignItems: 'center',
    justifyContent: 'center',
  },
  primaryActionBadgeText: {
    color: MENU_COLORS.primary,
    fontSize: 12,
    fontWeight: '700',
  },
  primaryActionContent: {
    flex: 1,
  },
  primaryActionTitle: {
    color: MENU_COLORS.primaryDark,
    fontSize: 15,
    fontWeight: '700',
    lineHeight: 20,
  },
  primaryActionTitleEmphasis: {
    fontSize: 16,
    letterSpacing: 0.2,
  },
  primaryActionSubtitle: {
    color: MENU_COLORS.textMuted,
    fontSize: 12,
    marginTop: 4,
    lineHeight: 16,
  },
  primaryActionSubtitleEmphasis: {
    color: MENU_COLORS.primary,
    fontWeight: '600',
  },
  primaryActionArrow: {
    color: MENU_COLORS.textMuted,
  },
  greetingTitle: {
    color: MENU_COLORS.primaryDark,
    fontSize: 20,
    fontWeight: '800',
    lineHeight: 26,
  },
  greetingSubtitle: {
    color: MENU_COLORS.textMuted,
    fontSize: 13,
    marginTop: 4,
    lineHeight: 18,
  },
  overlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0, 0, 0, 0.35)',
    zIndex: 2,
  },
  sidebar: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 0,
    width: 260,
    backgroundColor: '#F2FAFA',
    borderRightWidth: 1,
    borderRightColor: MENU_COLORS.border,
    paddingTop: MENU_CONFIG.spacing.xl,
    paddingHorizontal: MENU_CONFIG.spacing.lg,
    zIndex: 3,
  },
  sidebarHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: MENU_CONFIG.spacing.md,
    marginBottom: MENU_CONFIG.spacing.lg,
  },
  avatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: MENU_COLORS.primary,
  },
  sidebarTitle: {
    color: MENU_COLORS.text,
    fontSize: 16,
    fontWeight: '700',
  },
  sidebarSubtitle: {
    color: MENU_COLORS.textMuted,
    fontSize: 12,
    marginTop: 2,
  },
  menuList: {
    marginTop: MENU_CONFIG.spacing.sm,
    flex: 1,
  },
  menuFooter: {
    marginTop: 'auto',
    paddingTop: MENU_CONFIG.spacing.md,
  },
  menuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: MENU_CONFIG.spacing.md,
    paddingVertical: MENU_CONFIG.spacing.sm,
  },
  menuLabel: {
    color: MENU_COLORS.primaryDark,
    fontSize: 14,
    fontWeight: '600',
  },
  divider: {
    height: 1,
    backgroundColor: '#DCEDEE',
    marginVertical: MENU_CONFIG.spacing.md,
  },
  iconButton: {
    padding: MENU_CONFIG.spacing.md,
    alignItems: 'center',
    justifyContent: 'center',
  },
  icon: {
    color: MENU_COLORS.text,
  },
  bottomNav: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    height: 62,
    backgroundColor: MENU_COLORS.primary,
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
    zIndex: 1,
    shadowColor: MENU_COLORS.primaryDark,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.2,
    shadowRadius: 12,
    elevation: 6,
  },
  bottomNavFab: {
    position: 'absolute',
    top: -12,
    alignSelf: 'center',
    width: 58,
    height: 58,
    borderRadius: 29,
    backgroundColor: MENU_COLORS.surface,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: MENU_COLORS.primaryDark,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.2,
    shadowRadius: 10,
    elevation: 6,
  },
  bottomNavFabText: {
    color: MENU_COLORS.primary,
    fontSize: 24,
    fontWeight: '700',
  },
});
