export const REGISTER_COLORS = {
  primary: '#0E7C86',
  primaryDark: '#0A5C63',
  accent: '#59C6B3',
  background: '#F6FBFB',
  card: '#FFFFFF',
  text: '#0E2A2F',
  textSecondary: '#5C7B80',
  textMuted: '#A9B8BA',
  inputBackground: '#EFF6F6',
  border: '#D7E5E6',
  error: '#D93F3F',
  success: '#2D9D78',
  white: '#FFFFFF',
};

export const REGISTER_STRINGS = {
  title: 'Crea tu cuenta',
  subtitle: 'Completa tu perfil para comenzar',
  fullNameLabel: 'Nombre completo',
  fullNamePlaceholder: 'Tu nombre completo',
  emailLabel: 'Correo electrónico',
  emailPlaceholder: 'nombre@ejemplo.com',
  passwordLabel: 'Contraseña',
  passwordPlaceholder: 'Mínimo 8 caracteres',
  confirmPasswordLabel: 'Confirmar contraseña',
  confirmPasswordPlaceholder: 'Repite tu contraseña',
  birthDateLabel: 'Fecha de nacimiento',
  birthDatePlaceholder: 'DD/MM/AAAA',
  phoneLabel: 'Teléfono (opcional)',
  phonePlaceholder: '+52 55 1234 5678',
  termsText: 'Acepto términos y condiciones',
  privacyText: 'Acepto la política de privacidad',
  registerButton: 'Crear cuenta',
  backToLogin: '¿Ya tienes cuenta? Inicia sesión',
  successTitle: 'Cuenta creada',
  successMessage: 'Tu cuenta se creó correctamente.',
  validation: {
    fullNameRequired: 'El nombre completo es requerido',
    emailRequired: 'El correo es requerido',
    emailInvalid: 'El formato del correo es inválido',
    passwordRequired: 'La contraseña es requerida',
    passwordMinLength: 'La contraseña debe tener mínimo 8 caracteres',
    confirmPasswordRequired: 'Confirma tu contraseña',
    confirmPasswordMismatch: 'Las contraseñas no coinciden',
    birthDateRequired: 'La fecha de nacimiento es requerida',
    birthDateInvalid: 'La fecha debe usar el formato DD/MM/AAAA',
    termsRequired: 'Debes aceptar los términos y condiciones',
    privacyRequired: 'Debes aceptar la política de privacidad',
  },
};

export const REGISTER_CONFIG = {
  logoSize: 72,
  inputHeight: 52,
  buttonHeight: 52,
  borderRadius: 26,
  cardRadius: 28,
  spacing: { xs: 8, sm: 12, md: 16, lg: 24, xl: 32 },
};
